#!/usr/bin/env bash
set -euo pipefail

# ─── maistro-engine installer ──────────────────────────────────────────────
# One command: ./install.sh
# Installs Podman (rootless) if needed, generates secure defaults, starts the engine.
# Binds to localhost only. Generates a unique access token per deploy.
# ───────────────────────────────────────────────────────────────────────────

COMPOSE_FILE="docker-compose.yml"
ENV_FILE=".env"
BIND_HOST="127.0.0.1"
PORT="${MAISTRO_PORT:-8000}"

# ─── Colors ───────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

info()  { echo -e "${BLUE}[maistro]${NC} $*"; }
ok()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

# ─── Detect OS ────────────────────────────────────────────────────────────
detect_os() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if command -v apt-get &>/dev/null; then echo "debian"
        elif command -v dnf &>/dev/null; then echo "fedora"
        elif command -v pacman &>/dev/null; then echo "arch"
        else echo "linux-unknown"; fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then echo "macos"
    else echo "unknown"; fi
}

# ─── Install Podman ───────────────────────────────────────────────────────
install_podman() {
    local os="$1"
    info "Installing Podman (rootless container runtime)..."
    case "$os" in
        debian)
            sudo apt-get update -qq && sudo apt-get install -y -qq podman >/dev/null 2>&1
            ;;
        fedora)
            sudo dnf install -y -q podman >/dev/null 2>&1
            ;;
        arch)
            sudo pacman -Sy --noconfirm podman >/dev/null 2>&1
            ;;
        macos)
            if command -v brew &>/dev/null; then
                brew install podman >/dev/null 2>&1
                podman machine init --now 2>/dev/null || true
            else
                fail "Homebrew not found. Install Podman manually: https://podman.io/docs/installation"
            fi
            ;;
        *)
            fail "Cannot auto-install Podman on this OS. Install manually: https://podman.io/docs/installation"
            ;;
    esac
    ok "Podman installed"
}

# ─── Check / install container runtime ────────────────────────────────────
ensure_runtime() {
    if command -v podman &>/dev/null; then
        ok "Podman found: $(podman --version)"
        RUNTIME="podman"
    elif command -v docker &>/dev/null; then
        ok "Docker found (Podman preferred but Docker works)"
        RUNTIME="docker"
    else
        local os
        os=$(detect_os)
        install_podman "$os"
        RUNTIME="podman"
    fi

    # Verify compose support
    if ! $RUNTIME compose version &>/dev/null 2>&1; then
        if command -v podman-compose &>/dev/null; then
            COMPOSE_CMD="podman-compose"
        elif command -v docker-compose &>/dev/null; then
            COMPOSE_CMD="docker-compose"
        else
            info "Installing podman-compose..."
            pip3 install --quiet podman-compose 2>/dev/null || pip install --quiet podman-compose 2>/dev/null
            COMPOSE_CMD="podman-compose"
        fi
    else
        COMPOSE_CMD="$RUNTIME compose"
    fi
    ok "Compose: $COMPOSE_CMD"
}

# ─── Generate secure defaults ─────────────────────────────────────────────
generate_env() {
    if [[ -f "$ENV_FILE" ]]; then
        warn ".env exists — preserving. Delete it to regenerate."
        return
    fi

    local token
    token=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null \
         || openssl rand -base64 32 | tr -d '/+=' | head -c 43)

    local db_pass
    db_pass=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))" 2>/dev/null \
           || openssl rand -base64 16 | tr -d '/+=' | head -c 22)

    cat > "$ENV_FILE" <<EOF
# Generated by install.sh — do NOT commit this file.
# Regenerate: rm .env && ./install.sh

# ─── Security ───────────────────────────────────────────
# Access token required for all API/UI access.
MAISTRO_ACCESS_TOKEN=${token}

# Bind to localhost only. Set to 0.0.0.0 ONLY if you understand the risk.
MAISTRO_BIND_HOST=${BIND_HOST}
MAISTRO_PORT=${PORT}

# ─── Database ───────────────────────────────────────────
POSTGRES_PASSWORD=${db_pass}
DATABASE_URL=postgresql://maistro:${db_pass}@db:5432/maistro

# ─── LLM (configure at least one) ──────────────────────
# LITELLM_API_BASE=https://your-litellm-or-openai-compatible/v1
# LITELLM_API_KEY=sk-...
# CHAT_DEFAULT_MODEL=gpt-4o

# ─── Evolve (optional) ─────────────────────────────────
BENCHMARK_FIDELITY=proxy
EOF

    chmod 600 "$ENV_FILE"
    ok "Generated .env with unique access token"
}

# ─── Start ────────────────────────────────────────────────────────────────
start_engine() {
    info "Starting maistro-engine..."
    $COMPOSE_CMD -f "$COMPOSE_FILE" up -d --build 2>&1 | tail -5

    # Wait for health
    info "Waiting for engine to be healthy..."
    local attempts=0
    while ! curl -sf "http://${BIND_HOST}:${PORT}/health" >/dev/null 2>&1; do
        attempts=$((attempts + 1))
        if [[ $attempts -gt 30 ]]; then
            fail "Engine failed to start. Check: $COMPOSE_CMD logs maistro-engine"
        fi
        sleep 2
    done
    ok "Engine healthy"
}

# ─── Smoke test ───────────────────────────────────────────────────────────
smoke_test() {
    local token
    token=$(grep MAISTRO_ACCESS_TOKEN "$ENV_FILE" | cut -d= -f2)

    local status
    status=$(curl -sf -H "Authorization: Bearer $token" "http://${BIND_HOST}:${PORT}/v1/status" 2>/dev/null | python3 -c "import sys,json;print(json.load(sys.stdin).get('status',''))" 2>/dev/null || echo "")

    if [[ "$status" == "ok" ]]; then
        ok "Smoke test passed"
    else
        warn "Smoke test inconclusive (engine may still be initializing)"
    fi
}

# ─── Main ─────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo -e "${BLUE}┌────────────────────────────────────────────┐${NC}"
    echo -e "${BLUE}│  maistro-engine installer                  │${NC}"
    echo -e "${BLUE}│  Security-first agent runtime              │${NC}"
    echo -e "${BLUE}└────────────────────────────────────────────┘${NC}"
    echo ""

    ensure_runtime
    generate_env
    start_engine
    smoke_test

    local token
    token=$(grep MAISTRO_ACCESS_TOKEN "$ENV_FILE" | cut -d= -f2)

    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  maistro-engine is running${NC}"
    echo ""
    echo -e "  URL:   ${BLUE}http://${BIND_HOST}:${PORT}${NC}"
    echo -e "  Token: ${YELLOW}${token}${NC}"
    echo ""
    echo -e "  ${YELLOW}⚠  Bound to localhost only.${NC}"
    echo -e "  To expose: set MAISTRO_BIND_HOST=0.0.0.0 in .env"
    echo -e "  (only after reading docs/SECURITY.md)"
    echo ""
    echo -e "  Logs:  $COMPOSE_CMD logs -f maistro-engine"
    echo -e "  Stop:  $COMPOSE_CMD down"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

main "$@"
