"""maistro-canvas: standalone book builder with AI image generation pipeline.

Standalone product that can run on a mini-PC with a P40 image gen server.
Uses canvas protocols from maistro-core for the image generation pipeline.
"""

from __future__ import annotations

from maistro_canvas.layers import (
    Anchor,
    AssetDefinition,
    AssetInstance,
    AssetSheet,
    BackgroundComposition,
    CharacterPose,
    ChildProfile,
    FoundationFootprint,
    GroundPlane,
    LayerKind,
    OcclusionHint,
    POSE_GEOMETRY_FOR_KIND,
    PersonalizationKind,
    PersonalizationSlot,
    PoseGeometry,
    RenderStyle,
    Slot,
    Socket,
    StyleVolume,
    Transform,
    WheelAnchors,
    WorldStyle,
    WorldStylePartial,
    layer_type_to_kind,
    merge_world_style,
)
from maistro_canvas.protocols import (
    AssetRegistry,
    AssetSheetService,
    CanvasStore,
    CompositorService,
    ImageData,
    ImageGenClient,
    PersonalizationCompiler,
)
from maistro_canvas.types import (
    AssetDefinitionNotFoundError,
    AssetSheetNotFoundError,
    BlendMode,
    CanvasError,
    CanvasRecord,
    CanvasTier,
    GenerationJobRecord,
    JobAction,
    JobStatus,
    LayerRecord,
    LayerType,
    MissingAnchorError,
    MissingSocketError,
    ModelInfo,
    OcclusionCycleError,
    PoseGeometryMismatchError,
    SkinBindingError,
    TextConfig,
    UnknownLayerKindError,
    WorldStyleConflictError,
    normalise_rotation,
    validate_canvas_dimensions,
)

__all__ = [
    # Existing canvas primitives
    "BlendMode",
    "CanvasError",
    "CanvasRecord",
    "CanvasStore",
    "CanvasTier",
    "CompositorService",
    "GenerationJobRecord",
    "ImageData",
    "ImageGenClient",
    "JobAction",
    "JobStatus",
    "LayerRecord",
    "LayerType",
    "ModelInfo",
    "TextConfig",
    "validate_canvas_dimensions",
    "normalise_rotation",
    # ADR-039 layer model
    "Anchor",
    "AssetDefinition",
    "AssetInstance",
    "AssetRegistry",
    "AssetSheet",
    "AssetSheetService",
    "BackgroundComposition",
    "CharacterPose",
    "ChildProfile",
    "FoundationFootprint",
    "GroundPlane",
    "LayerKind",
    "OcclusionHint",
    "POSE_GEOMETRY_FOR_KIND",
    "PersonalizationCompiler",
    "PersonalizationKind",
    "PersonalizationSlot",
    "PoseGeometry",
    "RenderStyle",
    "Slot",
    "Socket",
    "StyleVolume",
    "Transform",
    "WheelAnchors",
    "WorldStyle",
    "WorldStylePartial",
    "layer_type_to_kind",
    "merge_world_style",
    # ADR-039 errors
    "AssetDefinitionNotFoundError",
    "AssetSheetNotFoundError",
    "MissingAnchorError",
    "MissingSocketError",
    "OcclusionCycleError",
    "PoseGeometryMismatchError",
    "SkinBindingError",
    "UnknownLayerKindError",
    "WorldStyleConflictError",
]
