"""maistro-design protocols — structural interfaces for DI."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from maistro_design.types import (
        DesignProject,
        DesignSkill,
        DesignSystem,
        DiscoveryResult,
    )


@runtime_checkable
class DesignSkillRegistry(Protocol):
    def register(self, skill: DesignSkill) -> None: ...
    def get(self, slug: str) -> DesignSkill | None: ...
    def list_all(self) -> list[DesignSkill]: ...
    def list_by_mode(self, mode: str) -> list[DesignSkill]: ...
    def list_featured(self) -> list[DesignSkill]: ...
    def delete(self, slug: str) -> bool: ...


@runtime_checkable
class DesignSystemRegistry(Protocol):
    def register(self, system: DesignSystem) -> None: ...
    def get(self, slug: str) -> DesignSystem | None: ...
    def list_all(self) -> list[DesignSystem]: ...
    def delete(self, slug: str) -> bool: ...


@runtime_checkable
class DesignProjectStore(Protocol):
    async def create(self, project: DesignProject) -> DesignProject: ...
    async def get(self, project_id: str) -> DesignProject | None: ...
    async def list_by_skill(self, skill_slug: str, org_id: str) -> list[DesignProject]: ...
    async def list_by_org(self, org_id: str) -> list[DesignProject]: ...
    async def update(self, project: DesignProject) -> DesignProject: ...
    async def delete(self, project_id: str) -> None: ...


@runtime_checkable
class DesignEngineProtocol(Protocol):
    async def run_discovery(self, skill_slug: str) -> list[dict]: ...
    async def generate(self, discovery: DiscoveryResult) -> DesignProject: ...
