"""Generate the canonical registry from validated front-matter.

Emits two artifacts:

- ``registry/registry.json`` — canonical machine-readable form. Sorted
  keys; deterministic for diff-friendly review.
- ``registry/registry.md`` — human-readable rendering grouped by repo.

Both are intended to be regenerated by CI on every merge to ``main``
once ``[engine-002]`` lands. Until then they're regenerated on demand
via ``maistro-registry generate``.

Back-references (``superseded_by``, ``blocked_by_inverse``,
``referenced_by``) are computed from the forward refs at build time.
This means a single run of `generate` produces a fully-cross-linked
registry.
"""

from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path

from maistro_registry.schema import FrontMatter


@dataclass
class RegistryEntry:
    """Serializable form of a single ADR/spec front-matter.

    The ``*_inverse`` fields are populated by ``Registry.compute_back_references``
    after all entries are added. They make the registry queryable in both
    directions without re-walking the forward refs.
    """

    id: str
    title: str
    repo: str
    kind: str
    status: str
    layer: str
    created: str
    accepted: str | None
    implemented: str | None
    substrate: list[str]
    implements: list[str]
    related: list[str]
    supersedes: list[str]
    blocks: list[str]
    blocked_by: list[str]
    contracts: list[str]
    tests: list[str]
    owners: list[str]
    # Computed back-references
    superseded_by: list[str] = field(default_factory=list)
    blocked_by_inverse: list[str] = field(default_factory=list)
    referenced_by: list[str] = field(default_factory=list)

    @classmethod
    def from_front_matter(cls, fm: FrontMatter) -> RegistryEntry:
        return cls(
            id=fm.id,
            title=fm.title,
            repo=fm.repo.value,
            kind=fm.kind.value,
            status=fm.status.value,
            layer=fm.layer.value,
            created=fm.created.isoformat(),
            accepted=fm.accepted.isoformat() if fm.accepted else None,
            implemented=fm.implemented.isoformat() if fm.implemented else None,
            substrate=list(fm.substrate),
            implements=list(fm.implements),
            related=list(fm.related),
            supersedes=list(fm.supersedes),
            blocks=list(fm.blocks),
            blocked_by=list(fm.blocked_by),
            contracts=[c.value for c in fm.contracts],
            tests=list(fm.tests),
            owners=list(fm.owners),
        )


@dataclass
class Registry:
    """Canonical registry: `<repo>#<id>` → entry."""

    entries: dict[str, RegistryEntry] = field(default_factory=dict)

    def add(self, fm: FrontMatter) -> None:
        ref = f"{fm.repo.value}#{fm.id}"
        self.entries[ref] = RegistryEntry.from_front_matter(fm)

    def compute_back_references(self) -> None:
        """Populate ``superseded_by`` / ``blocked_by_inverse`` / ``referenced_by``
        for every entry by walking forward refs.

        Idempotent: existing back-ref lists are cleared first so multiple
        invocations don't duplicate.
        """
        # Reset existing back-refs (idempotency)
        for entry in self.entries.values():
            entry.superseded_by = []
            entry.blocked_by_inverse = []
            entry.referenced_by = []

        for src_ref, entry in self.entries.items():
            for target in entry.supersedes:
                if target in self.entries:
                    self.entries[target].superseded_by.append(src_ref)
            for target in entry.blocks:
                if target in self.entries:
                    self.entries[target].blocked_by_inverse.append(src_ref)
            general_refs = entry.substrate + entry.related + entry.implements + entry.blocked_by
            for target in general_refs:
                if target in self.entries:
                    self.entries[target].referenced_by.append(src_ref)

        # Sort the back-ref lists for diff-friendly output
        for entry in self.entries.values():
            entry.superseded_by.sort()
            entry.blocked_by_inverse.sort()
            entry.referenced_by.sort()

    def to_json(self) -> str:
        """Render as JSON with sorted keys for deterministic diffs."""
        payload = {ref: asdict(entry) for ref, entry in sorted(self.entries.items())}
        return json.dumps(payload, indent=2, sort_keys=True)

    def to_markdown(self) -> str:
        """Render as a Markdown table grouped by repo."""
        by_repo: dict[str, list[RegistryEntry]] = defaultdict(list)
        for entry in self.entries.values():
            by_repo[entry.repo].append(entry)

        lines: list[str] = [
            "# Registry (auto-generated)",
            "",
            "Generated by `tools/registry/cli.py generate`.",
            "Do not hand-edit — changes will be overwritten.",
            "Convention defined in [`engine#ADR-031`](docs/adr/ADR-031-front-matter-and-registry.md).",
            "",
            f"**{len(self.entries)} artifacts** across {len(by_repo)} repos.",
            "",
        ]

        for repo in sorted(by_repo):
            entries = sorted(by_repo[repo], key=lambda e: e.id)
            lines.append(f"## `{repo}` ({len(entries)} artifacts)")
            lines.append("")
            lines.append("| ID | Title | Kind | Status | Layer |")
            lines.append("|---|---|---|---|---|")
            for e in entries:
                title = e.title.replace("|", "\\|")
                lines.append(f"| {e.id} | {title} | {e.kind} | {e.status} | {e.layer} |")
            lines.append("")

        return "\n".join(lines)


def build_registry(front_matters: list[FrontMatter]) -> Registry:
    """Build a Registry with back-references computed."""
    reg = Registry()
    for fm in front_matters:
        reg.add(fm)
    reg.compute_back_references()
    return reg


def write_registry(registry: Registry, output_dir: Path) -> tuple[Path, Path]:
    """Write `registry.json` + `registry.md` under ``output_dir``."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "registry.json"
    md_path = output_dir / "registry.md"
    json_path.write_text(registry.to_json() + "\n", encoding="utf-8")
    md_path.write_text(registry.to_markdown(), encoding="utf-8")
    return json_path, md_path
