"""Delivery-mode renderers: image_pull compose + per-mode Makefile.

`image_pull` must produce a **standalone** compose file with no `build:` keys
anywhere: an override merged onto the root compose cannot express "don't
build" (Compose merges mappings, so the base `build:` keys survive), and
`up --build` would still build from source. `source_build` keeps the root
compose but gets a Makefile pinning the exact invocations `install.sh` uses
(SPEC-072726-3439 Phase 2).
"""

from __future__ import annotations

import copy
import os
import subprocess
from pathlib import Path
from typing import Any

DEFAULT_IMAGE_REPOSITORY = "ghcr.io/agent-stronghold"
DEFAULT_IMAGE_TAG = "latest"

IMAGE_SERVICES = ("maistro-engine", "hive-conductor")


def image_tag() -> str:
    """Container tag the generated compose pins to.

    `MAISTRO_IMAGE_TAG` is set by get.sh/install.sh to the release tag the
    source tree was checked out at (E5/#298), so a `--version v1.0.0` install
    runs `v1.0.0` images rather than whatever `latest` happens to point at.
    Read at call time, not import time: the wizard runs as a subprocess of
    install.sh, and an import-time snapshot would freeze the value before the
    caller's environment is visible in tests.
    """
    return (os.environ.get("MAISTRO_IMAGE_TAG") or "").strip() or DEFAULT_IMAGE_TAG


def pinned_images() -> dict[str, str]:
    """Services in the root compose that carry build: keys, mapped to their
    published image references at the currently selected tag."""
    tag = image_tag()
    return {name: f"{DEFAULT_IMAGE_REPOSITORY}/{name}:{tag}" for name in IMAGE_SERVICES}


# Import-time snapshot at the default tag, kept for callers that want the
# mapping as a constant. Prefer pinned_images() — it reflects MAISTRO_IMAGE_TAG.
PINNED_IMAGES: dict[str, str] = pinned_images()


def render_image_pull_compose(
    base_compose: dict[str, Any], images: dict[str, str] | None = None
) -> dict[str, Any]:
    """Return a standalone compose document with every build: replaced by image:.

    Raises if a built service has no pinned image mapping — silently keeping
    its build: key would reintroduce the source build this mode exists to
    avoid.
    """
    image_map = {**pinned_images(), **(images or {})}
    doc = copy.deepcopy(base_compose)
    services = doc.get("services")
    if not isinstance(services, dict):
        raise ValueError("base compose has no services mapping")
    for name, svc in services.items():
        if not isinstance(svc, dict) or "build" not in svc:
            continue
        if name not in image_map:
            raise ValueError(f"no pinned image for built service {name!r}")
        svc.pop("build")
        svc["image"] = image_map[name]
    return doc


def git_revision(repo_root: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
    except OSError:
        return None
    rev = out.stdout.strip()
    return rev if out.returncode == 0 and rev else None


def render_makefile(
    mode: str,
    *,
    base_compose_path: str | None,
    revision: str | None,
) -> str:
    """Operator-facing Makefile wrapping the exact compose invocations.

    Recipes must be tab-indented — keep literal tabs in this template.
    """
    # --project-directory pins interpolation (.env) and relative bind-mount
    # resolution to the repo root, not this artifacts directory.
    project_dir = "."
    if base_compose_path:
        parent = str(Path(base_compose_path).parent)
        project_dir = parent if parent not in ("", ".") else "."
    if mode == "image_pull":
        compose = f"docker compose --project-directory {project_dir} -f compose.install.yml"
        up = f"{compose} up -d"
        update = f"{compose} pull\n\t{up}"
    else:
        base = base_compose_path or "<path-to-docker-compose.yml>"
        compose = (
            f"docker compose --project-directory {project_dir} -f {base} -f compose.override.yml"
        )
        up = f"{compose} up -d --build"
        update = up
    rev_line = f"# source revision: {revision}" if revision else "# source revision: (unknown)"
    return f"""# Generated by maistro-install — delivery_mode={mode}
{rev_line}
# Runtime behavior is identical across delivery modes; only how the
# maistro-engine and hive-conductor images arrive differs.

.PHONY: install up down logs status backup teardown update

install:
\t{compose} config --quiet
\t@echo "compose config OK — run 'make up'"

up:
\t{up}

down:
\t{compose} down

logs:
\t{compose} logs -f --tail=200

status:
\t{compose} ps

backup:
\t{compose} exec postgres pg_dump -U maistro maistro > maistro-backup-$$(date +%Y%m%d-%H%M%S).sql

teardown:
\t@echo "This deletes all volumes (database, conductor state). Ctrl-C to abort."
\t@sleep 5
\t{compose} down -v

update:
\t{update}
"""
